latest-changes

diff --git a/python-app/Makefile b/python-app/Makefile
--- a/python-app/Makefile
+++ b/python-app/Makefile
@@ -1,6 +1,6 @@
 # Variables
 TAG ?= 1.0.0  # Default semantic version, can be overridden via command line
-REGISTRY := ttl.sh
+REGISTRY := docker.io
 IMAGE_NAME := python-app
 CONTAINER_NAME := python-app-container
 
@@ -18,19 +18,23 @@ lint:
 
 # Docker login
 docker-login:
-	echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
+	@if [ -z "$(DOCKERHUB_USERNAME)" ] || [ -z "$(DOCKERHUB_TOKEN)" ]; then \
+		echo "Error: DOCKERHUB_USERNAME or DOCKERHUB_TOKEN is not set"; \
+		exit 1; \
+	fi
+	echo $(DOCKERHUB_TOKEN) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin
 
 # Build Docker image with semver tag
 docker-build:
-	docker build -t $(REGISTRY)/$(IMAGE_NAME):$(TAG) .
+	docker build -t $(REGISTRY)/$(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(TAG) .
 
 # Push Docker image to registry
 docker-push:
-	docker push $(REGISTRY)/$(IMAGE_NAME):$(TAG)
+	docker push $(REGISTRY)/$(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(TAG)
 
 # Run Flask app using the last pushed Docker image
 run:
-	docker run --rm -d -p 5000:5000 --name $(CONTAINER_NAME) $(REGISTRY)/$(IMAGE_NAME):$(TAG)
+	docker run --rm -d -p 5000:5000 --name $(CONTAINER_NAME) $(REGISTRY)/$(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(TAG)
 
 # Stop and remove the running container (cleanup)
 stop:
